version: "3"

services:
  postgres:
    image: "postgres:15.4-alpine3.18"
    container_name: "notifications-prostgres-db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgres
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d development'" ]
      interval: 2s
      timeout: 3s
      retries: 5

  application:
    container_name: "notifications-application"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    expose:
      - "55000"
    ports:
      - "55000:55000"
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:
